package com.zhku.meeting.mapper;

import com.zhku.meeting.entities.ShowStatus;
import java.util.List;

public interface ShowStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    int deleteByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    int insert(ShowStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    ShowStatus selectByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    List<ShowStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    int updateByPrimaryKey(ShowStatus row);
}