package com.example.meetingmanage.mapper;

import com.example.meetingmanage.entities.Department;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    Department selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jun 11 23:28:47 CST 2020
     */
    int updateByPrimaryKey(Department record);

    // 部门登录信息
    Department loginMessage(Department record);

    List<Department> selectByCondition(Department record);

    List<Department> duplicateCheck(Department record);

    // 通过编号查id
    Department seletByNo(String No);
}