package com.zhku.meeting.entities;

public class ShowStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.room_id
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.room_no
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private String roomNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.one
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean one;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.two
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean two;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.three
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean three;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.four
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean four;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.five
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean five;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.room_size
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Integer roomSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.air
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean air;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.projector
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    private Boolean projector;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.room_id
     *
     * @return the value of status.room_id
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.room_id
     *
     * @param roomId the value for status.room_id
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.room_no
     *
     * @return the value of status.room_no
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public String getRoomNo() {
        return roomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.room_no
     *
     * @param roomNo the value for status.room_no
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo == null ? null : roomNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.one
     *
     * @return the value of status.one
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.one
     *
     * @param one the value for status.one
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setOne(Boolean one) {
        this.one = one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.two
     *
     * @return the value of status.two
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.two
     *
     * @param two the value for status.two
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setTwo(Boolean two) {
        this.two = two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.three
     *
     * @return the value of status.three
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getThree() {
        return three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.three
     *
     * @param three the value for status.three
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setThree(Boolean three) {
        this.three = three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.four
     *
     * @return the value of status.four
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getFour() {
        return four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.four
     *
     * @param four the value for status.four
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setFour(Boolean four) {
        this.four = four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.five
     *
     * @return the value of status.five
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getFive() {
        return five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.five
     *
     * @param five the value for status.five
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setFive(Boolean five) {
        this.five = five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.room_size
     *
     * @return the value of status.room_size
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Integer getRoomSize() {
        return roomSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.room_size
     *
     * @param roomSize the value for status.room_size
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setRoomSize(Integer roomSize) {
        this.roomSize = roomSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.air
     *
     * @return the value of status.air
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getAir() {
        return air;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.air
     *
     * @param air the value for status.air
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setAir(Boolean air) {
        this.air = air;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.projector
     *
     * @return the value of status.projector
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public Boolean getProjector() {
        return projector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.projector
     *
     * @param projector the value for status.projector
     *
     * @mbg.generated Tue May 20 20:12:15 CST 2025
     */
    public void setProjector(Boolean projector) {
        this.projector = projector;
    }
}